const API_URL = 'https://api.pokemontcg.io/';
const CARDS_PER_PAGE = 10;
const PAGINATION_NUMBER_PER_PAGE = 5;
const TOTAL_NUMBER_OF_API_PAGES = 124;

export {
  API_URL, CARDS_PER_PAGE, PAGINATION_NUMBER_PER_PAGE, TOTAL_NUMBER_OF_API_PAGES,
};
